version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nestjs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: nestjs-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - nestjs-network

volumes:
  postgres_data:

networks:
  nestjs-network:
    driver: bridge
